services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: memory-postgres
    restart: always
    environment:
      POSTGRES_USER: memory_user
      POSTGRES_PASSWORD: Memory123!
      POSTGRES_DB: memory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memory_user -d memory_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres-memory-network
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1G

  mcp-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: memory_db
      POSTGRES_USER: memory_user
      POSTGRES_PASSWORD: Memory123!
      MCP_SERVER_HOST: 0.0.0.0
      MCP_SERVER_PORT: 3000
      HTTP_PORT: 8080
      LOG_LEVEL: info
      EMBEDDING_MODEL: mock
    ports:
      - "3000:3000"
      - "8080:8080"
    networks:
      - postgres-memory-network
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  postgres-memory-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local